version: '3.8'
services:
  db:
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - 5432:5432

  backend:
    build: ./backend
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/database
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    ports:
      - 8080:8080
  
  frontend:
    build: ./frontend
    ports:
      - 80:80