openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /vote/:
    get:
      tags:
      - vote-controller
      summary: Returns the string "Vote"
      operationId: voteIndex
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /poll/:
    get:
      tags:
      - poll-controller
      operationId: pollIndex
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /option/:
    get:
      tags:
      - option-controller
      operationId: optionIndex
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components: {}
